export interface Character {
  id: number;
  name: string;
  description: string;
  image: string;
  attributes: {
    isMale: boolean;
    isFictional: boolean;
    isFromMovie: boolean;
    isSuperhero: boolean;
    hasSuperpowers: boolean;
    isVillain: boolean;
    isDisney: boolean;
    isHuman: boolean;
    isFromBook: boolean;
    hasSidekick: boolean;
    isFromTVShow: boolean;
    isAnimated: boolean;
    canFly: boolean;
    isFunny: boolean;
    hasMagic: boolean;
    isHistorical: boolean;
    isAlive: boolean;
    isAmerican: boolean;
    isOlderThan50: boolean;
    wearsDistinctiveCostume: boolean;
    // New attributes for categories
    isFromGame?: boolean;
    isFromVideoGame?: boolean;
    isSportsRelated?: boolean;
    isMusician?: boolean;
    isPolitician?: boolean;
    isScientist?: boolean;
    isFromAnime?: boolean;
    // Add index signature to allow accessing by string key
    [key: string]: boolean | undefined;
  };
  // Add user-contributed flag and contributor info
  userContributed?: boolean;
  contributedBy?: string;
  dateAdded?: string;
}

export interface Question {
  id: number;
  text: string;
  attribute: string;
}

// Sample questions
export const questions: Question[] = [
  { id: 1, text: "Is your character male?", attribute: "isMale" },
  { id: 2, text: "Is your character fictional?", attribute: "isFictional" },
  { id: 3, text: "Is your character from a movie?", attribute: "isFromMovie" },
  { id: 4, text: "Is your character a superhero?", attribute: "isSuperhero" },
  { id: 5, text: "Does your character have superpowers?", attribute: "hasSuperpowers" },
  { id: 6, text: "Is your character a villain?", attribute: "isVillain" },
  { id: 7, text: "Is your character associated with Disney?", attribute: "isDisney" },
  { id: 8, text: "Is your character human?", attribute: "isHuman" },
  { id: 9, text: "Is your character from a book?", attribute: "isFromBook" },
  { id: 10, text: "Does your character have a sidekick?", attribute: "hasSidekick" },
  { id: 11, text: "Is your character from a TV show?", attribute: "isFromTVShow" },
  { id: 12, text: "Is your character animated?", attribute: "isAnimated" },
  { id: 13, text: "Can your character fly?", attribute: "canFly" },
  { id: 14, text: "Is your character known for being funny?", attribute: "isFunny" },
  { id: 15, text: "Is your character associated with magic?", attribute: "hasMagic" },
  { id: 16, text: "Is your character a historical figure?", attribute: "isHistorical" },
  { id: 17, text: "Is your character still alive?", attribute: "isAlive" },
  { id: 18, text: "Is your character American?", attribute: "isAmerican" },
  { id: 19, text: "Is your character older than 50 years?", attribute: "isOlderThan50" },
  { id: 20, text: "Does your character wear a distinctive costume?", attribute: "wearsDistinctiveCostume" },
  { id: 21, text: "Is your character from a video game?", attribute: "isFromVideoGame" },
  { id: 22, text: "Is your character related to sports?", attribute: "isSportsRelated" },
  { id: 23, text: "Is your character a musician?", attribute: "isMusician" },
  { id: 24, text: "Is your character a politician?", attribute: "isPolitician" },
  { id: 25, text: "Is your character a scientist?", attribute: "isScientist" },
  { id: 26, text: "Is your character from an anime?", attribute: "isFromAnime" },
];

// Sample characters database
export const characters: Character[] = [
  {
    id: 1,
    name: "Spider-Man",
    description: "A young superhero who gained spider-like abilities after being bitten by a radioactive spider.",
    image: "/characters/spiderman.jpg",
    attributes: {
      isMale: true,
      isFictional: true,
      isFromMovie: true,
      isSuperhero: true,
      hasSuperpowers: true,
      isVillain: false,
      isDisney: false,
      isHuman: true,
      isFromBook: true,
      hasSidekick: false,
      isFromTVShow: true,
      isAnimated: false,
      canFly: false,
      isFunny: true,
      hasMagic: false,
      isHistorical: false,
      isAlive: true,
      isAmerican: true,
      isOlderThan50: false,
      wearsDistinctiveCostume: true,
      isFromVideoGame: true,
      isFromGame: true,
    },
  },
  {
    id: 2,
    name: "Batman",
    description: "A wealthy vigilante who fights crime in Gotham City using his intellect and gadgets.",
    image: "/characters/batman.jpg",
    attributes: {
      isMale: true,
      isFictional: true,
      isFromMovie: true,
      isSuperhero: true,
      hasSuperpowers: false,
      isVillain: false,
      isDisney: false,
      isHuman: true,
      isFromBook: true,
      hasSidekick: true,
      isFromTVShow: true,
      isAnimated: false,
      canFly: false,
      isFunny: false,
      hasMagic: false,
      isHistorical: false,
      isAlive: true,
      isAmerican: true,
      isOlderThan50: false,
      wearsDistinctiveCostume: true,
      isFromVideoGame: true,
      isFromGame: true,
    },
  },
  {
    id: 3,
    name: "Wonder Woman",
    description: "An Amazonian princess with superhuman strength and other abilities.",
    image: "/characters/wonderwoman.jpg",
    attributes: {
      isMale: false,
      isFictional: true,
      isFromMovie: true,
      isSuperhero: true,
      hasSuperpowers: true,
      isVillain: false,
      isDisney: false,
      isHuman: false,
      isFromBook: true,
      hasSidekick: false,
      isFromTVShow: true,
      isAnimated: false,
      canFly: false,
      isFunny: false,
      hasMagic: false,
      isHistorical: false,
      isAlive: true,
      isAmerican: false,
      isOlderThan50: false,
      wearsDistinctiveCostume: true,
      isFromVideoGame: true,
      isFromGame: true,
    },
  },
  {
    id: 4,
    name: "Harry Potter",
    description: "A young wizard who attends Hogwarts School of Witchcraft and Wizardry.",
    image: "/characters/harrypotter.jpg",
    attributes: {
      isMale: true,
      isFictional: true,
      isFromMovie: true,
      isSuperhero: false,
      hasSuperpowers: false,
      isVillain: false,
      isDisney: false,
      isHuman: true,
      isFromBook: true,
      hasSidekick: true,
      isFromTVShow: false,
      isAnimated: false,
      canFly: true,
      isFunny: false,
      hasMagic: true,
      isHistorical: false,
      isAlive: true,
      isAmerican: false,
      isOlderThan50: false,
      wearsDistinctiveCostume: false,
      isFromVideoGame: true,
      isFromGame: true,
    },
  },
  {
    id: 5,
    name: "Darth Vader",
    description: "A powerful Sith Lord and the father of Luke Skywalker.",
    image: "/characters/darthvader.jpg",
    attributes: {
      isMale: true,
      isFictional: true,
      isFromMovie: true,
      isSuperhero: false,
      hasSuperpowers: true,
      isVillain: true,
      isDisney: true,
      isHuman: true,
      isFromBook: false,
      hasSidekick: false,
      isFromTVShow: true,
      isAnimated: false,
      canFly: false,
      isFunny: false,
      hasMagic: false,
      isHistorical: false,
      isAlive: false,
      isAmerican: false,
      isOlderThan50: false,
      wearsDistinctiveCostume: true,
      isFromVideoGame: true,
      isFromGame: true,
    },
  },
  {
    id: 6,
    name: "Mickey Mouse",
    description: "The iconic cartoon character and mascot of The Walt Disney Company.",
    image: "/characters/mickeymouse.jpg",
    attributes: {
      isMale: true,
      isFictional: true,
      isFromMovie: true,
      isSuperhero: false,
      hasSuperpowers: false,
      isVillain: false,
      isDisney: true,
      isHuman: false,
      isFromBook: false,
      hasSidekick: true,
      isFromTVShow: true,
      isAnimated: true,
      canFly: false,
      isFunny: true,
      hasMagic: false,
      isHistorical: false,
      isAlive: true,
      isAmerican: true,
      isOlderThan50: true,
      wearsDistinctiveCostume: false,
      isFromVideoGame: true,
      isFromGame: true,
    },
  },
  {
    id: 7,
    name: "Albert Einstein",
    description: "A theoretical physicist who developed the theory of relativity.",
    image: "/characters/einstein.jpg",
    attributes: {
      isMale: true,
      isFictional: false,
      isFromMovie: false,
      isSuperhero: false,
      hasSuperpowers: false,
      isVillain: false,
      isDisney: false,
      isHuman: true,
      isFromBook: false,
      hasSidekick: false,
      isFromTVShow: false,
      isAnimated: false,
      canFly: false,
      isFunny: false,
      hasMagic: false,
      isHistorical: true,
      isAlive: false,
      isAmerican: false,
      isOlderThan50: true,
      wearsDistinctiveCostume: false,
      isScientist: true,
    },
  },
  {
    id: 8,
    name: "Elsa",
    description: "The Snow Queen from Disney's Frozen with ice powers.",
    image: "/characters/elsa.jpg",
    attributes: {
      isMale: false,
      isFictional: true,
      isFromMovie: true,
      isSuperhero: false,
      hasSuperpowers: true,
      isVillain: false,
      isDisney: true,
      isHuman: true,
      isFromBook: false,
      hasSidekick: true,
      isFromTVShow: false,
      isAnimated: true,
      canFly: false,
      isFunny: false,
      hasMagic: true,
      isHistorical: false,
      isAlive: true,
      isAmerican: false,
      isOlderThan50: false,
      wearsDistinctiveCostume: true,
      isFromVideoGame: true,
      isFromGame: true,
    },
  },
  {
    id: 9,
    name: "Walter White",
    description: "A chemistry teacher turned methamphetamine producer from Breaking Bad.",
    image: "/characters/walterwhite.jpg",
    attributes: {
      isMale: true,
      isFictional: true,
      isFromMovie: false,
      isSuperhero: false,
      hasSuperpowers: false,
      isVillain: true,
      isDisney: false,
      isHuman: true,
      isFromBook: false,
      hasSidekick: true,
      isFromTVShow: true,
      isAnimated: false,
      canFly: false,
      isFunny: false,
      hasMagic: false,
      isHistorical: false,
      isAlive: false,
      isAmerican: true,
      isOlderThan50: true,
      wearsDistinctiveCostume: false,
      isScientist: true,
    },
  },
  {
    id: 10,
    name: "Mario",
    description: "The iconic plumber and Nintendo's mascot who saves Princess Peach.",
    image: "/characters/mario.jpg",
    attributes: {
      isMale: true,
      isFictional: true,
      isFromMovie: true,
      isSuperhero: false,
      hasSuperpowers: true,
      isVillain: false,
      isDisney: false,
      isHuman: true,
      isFromBook: false,
      hasSidekick: true,
      isFromTVShow: false,
      isAnimated: true,
      canFly: false,
      isFunny: false,
      hasMagic: false,
      isHistorical: false,
      isAlive: true,
      isAmerican: false,
      isOlderThan50: true,
      wearsDistinctiveCostume: true,
      isFromVideoGame: true,
      isFromGame: true,
    },
  },
  {
    id: 11,
    name: "Sherlock Holmes",
    description: "A brilliant detective known for his logical reasoning and deductive abilities.",
    image: "/characters/sherlockholmes.jpg",
    attributes: {
      isMale: true,
      isFictional: true,
      isFromMovie: true,
      isSuperhero: false,
      hasSuperpowers: false,
      isVillain: false,
      isDisney: false,
      isHuman: true,
      isFromBook: true,
      hasSidekick: true,
      isFromTVShow: true,
      isAnimated: false,
      canFly: false,
      isFunny: false,
      hasMagic: false,
      isHistorical: false,
      isAlive: true,
      isAmerican: false,
      isOlderThan50: true,
      wearsDistinctiveCostume: false,
    },
  },
  {
    id: 12,
    name: "Joker",
    description: "Batman's archenemy and a psychopathic criminal mastermind.",
    image: "/characters/joker.jpg",
    attributes: {
      isMale: true,
      isFictional: true,
      isFromMovie: true,
      isSuperhero: false,
      hasSuperpowers: false,
      isVillain: true,
      isDisney: false,
      isHuman: true,
      isFromBook: true,
      hasSidekick: true,
      isFromTVShow: true,
      isAnimated: false,
      canFly: false,
      isFunny: true,
      hasMagic: false,
      isHistorical: false,
      isAlive: true,
      isAmerican: true,
      isOlderThan50: false,
      wearsDistinctiveCostume: true,
      isFromVideoGame: true,
      isFromGame: true,
    },
  },
  {
    id: 13,
    name: "Daenerys Targaryen",
    description: "A character from Game of Thrones who seeks to reclaim the Iron Throne.",
    image: "/characters/daenerys.jpg",
    attributes: {
      isMale: false,
      isFictional: true,
      isFromMovie: false,
      isSuperhero: false,
      hasSuperpowers: false,
      isVillain: false,
      isDisney: false,
      isHuman: true,
      isFromBook: true,
      hasSidekick: false,
      isFromTVShow: true,
      isAnimated: false,
      canFly: false,
      isFunny: false,
      hasMagic: false,
      isHistorical: false,
      isAlive: false,
      isAmerican: false,
      isOlderThan50: false,
      wearsDistinctiveCostume: false,
    },
  },
  {
    id: 14,
    name: "Captain Jack Sparrow",
    description: "A witty and eccentric pirate captain from the Pirates of the Caribbean series.",
    image: "/characters/jacksparrow.jpg",
    attributes: {
      isMale: true,
      isFictional: true,
      isFromMovie: true,
      isSuperhero: false,
      hasSuperpowers: false,
      isVillain: false,
      isDisney: true,
      isHuman: true,
      isFromBook: false,
      hasSidekick: false,
      isFromTVShow: false,
      isAnimated: false,
      canFly: false,
      isFunny: true,
      hasMagic: false,
      isHistorical: false,
      isAlive: true,
      isAmerican: false,
      isOlderThan50: false,
      wearsDistinctiveCostume: true,
      isFromVideoGame: true,
      isFromGame: true,
    },
  },
  {
    id: 15,
    name: "Iron Man",
    description: "A genius inventor who created a powered suit of armor.",
    image: "/characters/ironman.jpg",
    attributes: {
      isMale: true,
      isFictional: true,
      isFromMovie: true,
      isSuperhero: true,
      hasSuperpowers: false,
      isVillain: false,
      isDisney: true,
      isHuman: true,
      isFromBook: true,
      hasSidekick: false,
      isFromTVShow: false,
      isAnimated: false,
      canFly: true,
      isFunny: true,
      hasMagic: false,
      isHistorical: false,
      isAlive: false,
      isAmerican: true,
      isOlderThan50: false,
      wearsDistinctiveCostume: true,
      isFromVideoGame: true,
      isFromGame: true,
      isScientist: true,
    },
  },
  {
    id: 16,
    name: "Hermione Granger",
    description: "A talented witch and one of Harry Potter's best friends.",
    image: "/characters/hermione.jpg",
    attributes: {
      isMale: false,
      isFictional: true,
      isFromMovie: true,
      isSuperhero: false,
      hasSuperpowers: false,
      isVillain: false,
      isDisney: false,
      isHuman: true,
      isFromBook: true,
      hasSidekick: false,
      isFromTVShow: false,
      isAnimated: false,
      canFly: true,
      isFunny: false,
      hasMagic: true,
      isHistorical: false,
      isAlive: true,
      isAmerican: false,
      isOlderThan50: false,
      wearsDistinctiveCostume: false,
      isFromVideoGame: true,
      isFromGame: true,
    },
  },
  {
    id: 17,
    name: "Thanos",
    description: "A powerful villain who sought to collect all Infinity Stones.",
    image: "/characters/thanos.jpg",
    attributes: {
      isMale: true,
      isFictional: true,
      isFromMovie: true,
      isSuperhero: false,
      hasSuperpowers: true,
      isVillain: true,
      isDisney: true,
      isHuman: false,
      isFromBook: true,
      hasSidekick: true,
      isFromTVShow: false,
      isAnimated: false,
      canFly: false,
      isFunny: false,
      hasMagic: false,
      isHistorical: false,
      isAlive: false,
      isAmerican: false,
      isOlderThan50: false,
      wearsDistinctiveCostume: true,
      isFromVideoGame: true,
      isFromGame: true,
    },
  },
  {
    id: 18,
    name: "Michael Jordan",
    description: "A legendary basketball player considered one of the greatest of all time.",
    image: "/characters/michaeljordan.jpg",
    attributes: {
      isMale: true,
      isFictional: false,
      isFromMovie: true,
      isSuperhero: false,
      hasSuperpowers: false,
      isVillain: false,
      isDisney: false,
      isHuman: true,
      isFromBook: false,
      hasSidekick: false,
      isFromTVShow: false,
      isAnimated: false,
      canFly: false,
      isFunny: false,
      hasMagic: false,
      isHistorical: true,
      isAlive: true,
      isAmerican: true,
      isOlderThan50: true,
      wearsDistinctiveCostume: false,
      isSportsRelated: true,
    },
  },
  {
    id: 19,
    name: "Gollum",
    description: "A creature corrupted by the One Ring in The Lord of the Rings.",
    image: "/characters/gollum.jpg",
    attributes: {
      isMale: true,
      isFictional: true,
      isFromMovie: true,
      isSuperhero: false,
      hasSuperpowers: false,
      isVillain: true,
      isDisney: false,
      isHuman: false,
      isFromBook: true,
      hasSidekick: false,
      isFromTVShow: false,
      isAnimated: false,
      canFly: false,
      isFunny: false,
      hasMagic: false,
      isHistorical: false,
      isAlive: false,
      isAmerican: false,
      isOlderThan50: false,
      wearsDistinctiveCostume: false,
      isFromVideoGame: true,
      isFromGame: true,
    },
  },
  {
    id: 20,
    name: "Maleficent",
    description: "A powerful fairy and the main antagonist in Sleeping Beauty.",
    image: "/characters/maleficent.jpg",
    attributes: {
      isMale: false,
      isFictional: true,
      isFromMovie: true,
      isSuperhero: false,
      hasSuperpowers: true,
      isVillain: true,
      isDisney: true,
      isHuman: false,
      isFromBook: false,
      hasSidekick: true,
      isFromTVShow: false,
      isAnimated: true,
      canFly: false,
      isFunny: false,
      hasMagic: true,
      isHistorical: false,
      isAlive: true,
      isAmerican: false,
      isOlderThan50: true,
      wearsDistinctiveCostume: true,
    },
  },
  {
    id: 21,
    name: "Cristiano Ronaldo",
    description: "One of the greatest football (soccer) players of all time.",
    image: "/characters/ronaldo.jpg",
    attributes: {
      isMale: true,
      isFictional: false,
      isFromMovie: false,
      isSuperhero: false,
      hasSuperpowers: false,
      isVillain: false,
      isDisney: false,
      isHuman: true,
      isFromBook: false,
      hasSidekick: false,
      isFromTVShow: false,
      isAnimated: false,
      canFly: false,
      isFunny: false,
      hasMagic: false,
      isHistorical: false,
      isAlive: true,
      isAmerican: false,
      isOlderThan50: false,
      wearsDistinctiveCostume: false,
      isSportsRelated: true,
    },
  },
  {
    id: 22,
    name: "Naruto Uzumaki",
    description: "A young ninja who dreams of becoming the leader of his village.",
    image: "/characters/naruto.jpg",
    attributes: {
      isMale: true,
      isFictional: true,
      isFromMovie: false,
      isSuperhero: false,
      hasSuperpowers: true,
      isVillain: false,
      isDisney: false,
      isHuman: true,
      isFromBook: false,
      hasSidekick: true,
      isFromTVShow: true,
      isAnimated: true,
      canFly: false,
      isFunny: true,
      hasMagic: false,
      isHistorical: false,
      isAlive: true,
      isAmerican: false,
      isOlderThan50: false,
      wearsDistinctiveCostume: true,
      isFromAnime: true,
      isFromVideoGame: true,
      isFromGame: true,
    },
  },
  {
    id: 23,
    name: "Master Chief",
    description: "A super soldier and the main protagonist of the Halo video game series.",
    image: "/characters/masterchief.jpg",
    attributes: {
      isMale: true,
      isFictional: true,
      isFromMovie: false,
      isSuperhero: true,
      hasSuperpowers: true,
      isVillain: false,
      isDisney: false,
      isHuman: true,
      isFromBook: false,
      hasSidekick: true,
      isFromTVShow: true,
      isAnimated: false,
      canFly: false,
      isFunny: false,
      hasMagic: false,
      isHistorical: false,
      isAlive: true,
      isAmerican: true,
      isOlderThan50: false,
      wearsDistinctiveCostume: true,
      isFromVideoGame: true,
      isFromGame: true,
    },
  },
  {
    id: 24,
    name: "Barack Obama",
    description: "The 44th President of the United States.",
    image: "/characters/obama.jpg",
    attributes: {
      isMale: true,
      isFictional: false,
      isFromMovie: false,
      isSuperhero: false,
      hasSuperpowers: false,
      isVillain: false,
      isDisney: false,
      isHuman: true,
      isFromBook: false,
      hasSidekick: false,
      isFromTVShow: false,
      isAnimated: false,
      canFly: false,
      isFunny: true,
      hasMagic: false,
      isHistorical: true,
      isAlive: true,
      isAmerican: true,
      isOlderThan50: true,
      wearsDistinctiveCostume: false,
      isPolitician: true,
    },
  },
  {
    id: 25,
    name: "Freddie Mercury",
    description: "The legendary lead vocalist of the rock band Queen.",
    image: "/characters/freddiemercury.jpg",
    attributes: {
      isMale: true,
      isFictional: false,
      isFromMovie: true,
      isSuperhero: false,
      hasSuperpowers: false,
      isVillain: false,
      isDisney: false,
      isHuman: true,
      isFromBook: false,
      hasSidekick: false,
      isFromTVShow: false,
      isAnimated: false,
      canFly: false,
      isFunny: false,
      hasMagic: false,
      isHistorical: true,
      isAlive: false,
      isAmerican: false,
      isOlderThan50: true,
      wearsDistinctiveCostume: true,
      isMusician: true,
    },
  },
];
